// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'63c2d8ff61b4b4ad40f8f7e3a0e5d7818fad0e10de4bdb601d8a64d478e6c136'>;
export type ExecutionHash =
  ExecutionHashBase<'31490cace67e0acff3f4194bd11452105da53384c653f35c612d64b8c59507ac'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly categorias: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly titulo: CodecTypes['pg/text@1']['output'];
      readonly url: CodecTypes['pg/text@1']['output'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly pedidos: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly usuario_id: CodecTypes['pg/int4@1']['output'];
      readonly producto_id: CodecTypes['pg/int4@1']['output'];
      readonly cantidad: CodecTypes['pg/int4@1']['output'];
      readonly total: CodecTypes['pg/float8@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly productos: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly titulo: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'];
      readonly url: CodecTypes['pg/text@1']['output'];
      readonly precio_compra: CodecTypes['pg/float8@1']['output'];
      readonly precio_venta: CodecTypes['pg/float8@1']['output'];
      readonly stock: CodecTypes['pg/int4@1']['output'];
      readonly imagen: CodecTypes['pg/text@1']['output'] | null;
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly usuarios: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly apellido: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly contrasena: CodecTypes['pg/text@1']['output'];
      readonly rol: CodecTypes['pg/text@1']['output'];
      readonly activo: CodecTypes['pg/bool@1']['output'] | null;
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly categorias: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly titulo: CodecTypes['pg/text@1']['input'];
      readonly url: CodecTypes['pg/text@1']['input'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly pedidos: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly usuario_id: CodecTypes['pg/int4@1']['input'];
      readonly producto_id: CodecTypes['pg/int4@1']['input'];
      readonly cantidad: CodecTypes['pg/int4@1']['input'];
      readonly total: CodecTypes['pg/float8@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly productos: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly titulo: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'];
      readonly url: CodecTypes['pg/text@1']['input'];
      readonly precio_compra: CodecTypes['pg/float8@1']['input'];
      readonly precio_venta: CodecTypes['pg/float8@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
      readonly imagen: CodecTypes['pg/text@1']['input'] | null;
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly usuarios: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly apellido: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly contrasena: CodecTypes['pg/text@1']['input'];
      readonly rol: CodecTypes['pg/text@1']['input'];
      readonly activo: CodecTypes['pg/bool@1']['input'] | null;
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly categorias: {
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly titulo: CodecTypes['pg/text@1']['output'];
      readonly url: CodecTypes['pg/text@1']['output'];
    };
    readonly pedidos: {
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly cantidad: CodecTypes['pg/int4@1']['output'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly producto_id: CodecTypes['pg/int4@1']['output'];
      readonly total: CodecTypes['pg/float8@1']['output'];
      readonly usuario_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly productos: {
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly descripcion: CodecTypes['pg/text@1']['output'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly imagen: CodecTypes['pg/text@1']['output'] | null;
      readonly precio_compra: CodecTypes['pg/float8@1']['output'];
      readonly precio_venta: CodecTypes['pg/float8@1']['output'];
      readonly stock: CodecTypes['pg/int4@1']['output'];
      readonly titulo: CodecTypes['pg/text@1']['output'];
      readonly url: CodecTypes['pg/text@1']['output'];
    };
    readonly usuarios: {
      readonly activo: CodecTypes['pg/bool@1']['output'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly apellido: CodecTypes['pg/text@1']['output'];
      readonly contrasena: CodecTypes['pg/text@1']['output'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly rol: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly categorias: {
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly creado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly titulo: CodecTypes['pg/text@1']['input'];
      readonly url: CodecTypes['pg/text@1']['input'];
    };
    readonly pedidos: {
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly cantidad: CodecTypes['pg/int4@1']['input'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly producto_id: CodecTypes['pg/int4@1']['input'];
      readonly total: CodecTypes['pg/float8@1']['input'];
      readonly usuario_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly productos: {
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly creado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly descripcion: CodecTypes['pg/text@1']['input'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly imagen: CodecTypes['pg/text@1']['input'] | null;
      readonly precio_compra: CodecTypes['pg/float8@1']['input'];
      readonly precio_venta: CodecTypes['pg/float8@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
      readonly titulo: CodecTypes['pg/text@1']['input'];
      readonly url: CodecTypes['pg/text@1']['input'];
    };
    readonly usuarios: {
      readonly activo: CodecTypes['pg/bool@1']['input'] | null;
      readonly actualizado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly apellido: CodecTypes['pg/text@1']['input'];
      readonly contrasena: CodecTypes['pg/text@1']['input'];
      readonly creado_por_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly rol: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_usuarios = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    apellido: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    contrasena: CodecTypes['pg/text@1']['output'];
    rol: CodecTypes['pg/text@1']['output'];
    activo: CodecTypes['pg/bool@1']['output'] | null;
    fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
    fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
    creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    actualizado_por: public_usuarios | null;
    actualizados: public_usuarios[];
    categorias_actualizadas: public_categorias[];
    categorias_creadas: public_categorias[];
    creado_por: public_usuarios | null;
    creados: public_usuarios[];
    pedidos: public_pedidos[];
    pedidos_actualizados: public_pedidos[];
    pedidos_creados: public_pedidos[];
    productos_actualizados: public_productos[];
    productos_creados: public_productos[];
    readonly [RelationKeys]?:
      | 'actualizado_por'
      | 'actualizados'
      | 'categorias_actualizadas'
      | 'categorias_creadas'
      | 'creado_por'
      | 'creados'
      | 'pedidos'
      | 'pedidos_actualizados'
      | 'pedidos_creados'
      | 'productos_actualizados'
      | 'productos_creados';
  };
  export type public_categorias = {
    id: CodecTypes['pg/int4@1']['output'];
    titulo: CodecTypes['pg/text@1']['output'];
    url: CodecTypes['pg/text@1']['output'];
    fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
    fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
    creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    actualizado_por: public_usuarios | null;
    creado_por: public_usuarios | null;
    readonly [RelationKeys]?: 'actualizado_por' | 'creado_por';
  };
  export type public_productos = {
    id: CodecTypes['pg/int4@1']['output'];
    titulo: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'];
    url: CodecTypes['pg/text@1']['output'];
    precio_compra: CodecTypes['pg/float8@1']['output'];
    precio_venta: CodecTypes['pg/float8@1']['output'];
    stock: CodecTypes['pg/int4@1']['output'];
    imagen: CodecTypes['pg/text@1']['output'] | null;
    fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
    fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
    creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    actualizado_por: public_usuarios | null;
    creado_por: public_usuarios | null;
    pedidos: public_pedidos[];
    readonly [RelationKeys]?: 'actualizado_por' | 'creado_por' | 'pedidos';
  };
  export type public_pedidos = {
    id: CodecTypes['pg/int4@1']['output'];
    usuario_id: CodecTypes['pg/int4@1']['output'];
    producto_id: CodecTypes['pg/int4@1']['output'];
    cantidad: CodecTypes['pg/int4@1']['output'];
    total: CodecTypes['pg/float8@1']['output'];
    estado: CodecTypes['pg/text@1']['output'];
    fecha_creacion: CodecTypes['pg/timestamptz-string@1']['output'];
    fecha_actualizacion: CodecTypes['pg/timestamptz-string@1']['output'];
    creado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    actualizado_por_id: CodecTypes['pg/int4@1']['output'] | null;
    actualizado_por: public_usuarios | null;
    creado_por: public_usuarios | null;
    producto: public_productos;
    usuario: public_usuarios;
    readonly [RelationKeys]?: 'actualizado_por' | 'creado_por' | 'producto' | 'usuario';
  };
}

export declare const models: {
  public: {
    usuarios: Models.public_usuarios;
    categorias: Models.public_categorias;
    productos: Models.public_productos;
    pedidos: Models.public_pedidos;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly categorias: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly titulo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fecha_creacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly fecha_actualizacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly creado_por_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly actualizado_por_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['url'] }];
              indexes: readonly [
                {
                  readonly name: 'categorias_creado_por_id_idx_9be71d7d';
                  readonly prefix: 'categorias_creado_por_id_idx';
                  readonly columns: readonly ['creado_por_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'categorias_actualizado_por_id_idx_941f4e34';
                  readonly prefix: 'categorias_actualizado_por_id_idx';
                  readonly columns: readonly ['actualizado_por_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'categorias';
                    readonly columns: readonly ['creado_por_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'categorias';
                    readonly columns: readonly ['actualizado_por_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly pedidos: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly usuario_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly producto_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly cantidad: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly total: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fecha_creacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly fecha_actualizacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly creado_por_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly actualizado_por_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'pedidos_usuario_id_idx_65b6616a';
                  readonly prefix: 'pedidos_usuario_id_idx';
                  readonly columns: readonly ['usuario_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pedidos_producto_id_idx_52b7577c';
                  readonly prefix: 'pedidos_producto_id_idx';
                  readonly columns: readonly ['producto_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pedidos_creado_por_id_idx_9be71d7d';
                  readonly prefix: 'pedidos_creado_por_id_idx';
                  readonly columns: readonly ['creado_por_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pedidos_actualizado_por_id_idx_941f4e34';
                  readonly prefix: 'pedidos_actualizado_por_id_idx';
                  readonly columns: readonly ['actualizado_por_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pedidos';
                    readonly columns: readonly ['usuario_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pedidos';
                    readonly columns: readonly ['producto_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'productos';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pedidos';
                    readonly columns: readonly ['creado_por_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pedidos';
                    readonly columns: readonly ['actualizado_por_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly productos: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly titulo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly precio_compra: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly precio_venta: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly stock: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly imagen: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly fecha_creacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly fecha_actualizacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly creado_por_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly actualizado_por_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['url'] }];
              indexes: readonly [
                {
                  readonly name: 'productos_creado_por_id_idx_9be71d7d';
                  readonly prefix: 'productos_creado_por_id_idx';
                  readonly columns: readonly ['creado_por_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'productos_actualizado_por_id_idx_941f4e34';
                  readonly prefix: 'productos_actualizado_por_id_idx';
                  readonly columns: readonly ['actualizado_por_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'productos';
                    readonly columns: readonly ['creado_por_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'productos';
                    readonly columns: readonly ['actualizado_por_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly usuarios: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly apellido: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly contrasena: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly rol: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly fecha_creacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly fecha_actualizacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly creado_por_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly actualizado_por_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [
                {
                  readonly name: 'usuarios_creado_por_id_idx_9be71d7d';
                  readonly prefix: 'usuarios_creado_por_id_idx';
                  readonly columns: readonly ['creado_por_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'usuarios_actualizado_por_id_idx_941f4e34';
                  readonly prefix: 'usuarios_actualizado_por_id_idx';
                  readonly columns: readonly ['actualizado_por_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['creado_por_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['actualizado_por_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly usuarios: { readonly namespace: 'public' & NamespaceId; readonly model: 'usuarios' };
    readonly categorias: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'categorias';
    };
    readonly productos: { readonly namespace: 'public' & NamespaceId; readonly model: 'productos' };
    readonly pedidos: { readonly namespace: 'public' & NamespaceId; readonly model: 'pedidos' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly categorias: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly titulo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly url: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fecha_creacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly fecha_actualizacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly creado_por_id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly actualizado_por_id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly actualizado_por: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['actualizado_por_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly creado_por: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['creado_por_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'categorias';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly titulo: { readonly column: 'titulo' };
                readonly url: { readonly column: 'url' };
                readonly fecha_creacion: { readonly column: 'fecha_creacion' };
                readonly fecha_actualizacion: { readonly column: 'fecha_actualizacion' };
                readonly creado_por_id: { readonly column: 'creado_por_id' };
                readonly actualizado_por_id: { readonly column: 'actualizado_por_id' };
              };
            };
          };
          readonly pedidos: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly usuario_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly producto_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly cantidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly total: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fecha_creacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly fecha_actualizacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly creado_por_id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly actualizado_por_id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly actualizado_por: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['actualizado_por_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly creado_por: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['creado_por_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly producto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'productos';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['producto_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['usuario_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pedidos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly usuario_id: { readonly column: 'usuario_id' };
                readonly producto_id: { readonly column: 'producto_id' };
                readonly cantidad: { readonly column: 'cantidad' };
                readonly total: { readonly column: 'total' };
                readonly estado: { readonly column: 'estado' };
                readonly fecha_creacion: { readonly column: 'fecha_creacion' };
                readonly fecha_actualizacion: { readonly column: 'fecha_actualizacion' };
                readonly creado_por_id: { readonly column: 'creado_por_id' };
                readonly actualizado_por_id: { readonly column: 'actualizado_por_id' };
              };
            };
          };
          readonly productos: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly titulo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly url: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly precio_compra: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly precio_venta: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly imagen: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fecha_creacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly fecha_actualizacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly creado_por_id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly actualizado_por_id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly actualizado_por: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['actualizado_por_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly creado_por: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['creado_por_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly pedidos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'pedidos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['producto_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'productos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly titulo: { readonly column: 'titulo' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly url: { readonly column: 'url' };
                readonly precio_compra: { readonly column: 'precio_compra' };
                readonly precio_venta: { readonly column: 'precio_venta' };
                readonly stock: { readonly column: 'stock' };
                readonly imagen: { readonly column: 'imagen' };
                readonly fecha_creacion: { readonly column: 'fecha_creacion' };
                readonly fecha_actualizacion: { readonly column: 'fecha_actualizacion' };
                readonly creado_por_id: { readonly column: 'creado_por_id' };
                readonly actualizado_por_id: { readonly column: 'actualizado_por_id' };
              };
            };
          };
          readonly usuarios: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly apellido: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contrasena: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rol: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly fecha_creacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly fecha_actualizacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly creado_por_id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly actualizado_por_id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly actualizado_por: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['actualizado_por_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly actualizados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['actualizado_por_id'];
                };
              };
              readonly categorias_actualizadas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'categorias';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['actualizado_por_id'];
                };
              };
              readonly categorias_creadas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'categorias';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['creado_por_id'];
                };
              };
              readonly creado_por: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['creado_por_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly creados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuarios';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['creado_por_id'];
                };
              };
              readonly pedidos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'pedidos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuario_id'];
                };
              };
              readonly pedidos_actualizados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'pedidos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['actualizado_por_id'];
                };
              };
              readonly pedidos_creados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'pedidos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['creado_por_id'];
                };
              };
              readonly productos_actualizados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'productos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['actualizado_por_id'];
                };
              };
              readonly productos_creados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'productos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['creado_por_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuarios';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly apellido: { readonly column: 'apellido' };
                readonly email: { readonly column: 'email' };
                readonly contrasena: { readonly column: 'contrasena' };
                readonly rol: { readonly column: 'rol' };
                readonly activo: { readonly column: 'activo' };
                readonly fecha_creacion: { readonly column: 'fecha_creacion' };
                readonly fecha_actualizacion: { readonly column: 'fecha_actualizacion' };
                readonly creado_por_id: { readonly column: 'creado_por_id' };
                readonly actualizado_por_id: { readonly column: 'actualizado_por_id' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'categorias';
            readonly column: 'fecha_actualizacion';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'pedidos';
            readonly column: 'fecha_actualizacion';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'productos';
            readonly column: 'fecha_actualizacion';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'usuarios';
            readonly column: 'fecha_actualizacion';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
